const dinosaurs = [
    // ═══════════════════ TRIASSIC ═══════════════════
    { name: "Herrerasaurus", era: "Triassic", diet: "Carnivore", length: "6m", weight: "350kg", speed: "35 km/h", habitat: "Woodlands", discovered: "1958", dangerLevel: 7, funFact: "One of the earliest known dinosaurs, it was already a formidable predator with serrated teeth.", image: "images/dinos/herrerasaurus.jpg" },
    { name: "Coelophysis", era: "Triassic", diet: "Carnivore", length: "3m", weight: "20kg", speed: "45 km/h", habitat: "Arid Plains", discovered: "1889", dangerLevel: 4, funFact: "Hundreds of skeletons were found at Ghost Ranch, New Mexico — one of the largest dinosaur graveyards ever.", image: "images/dinos/coelophysis.jpg" },
    { name: "Plateosaurus", era: "Triassic", diet: "Herbivore", length: "8m", weight: "4000kg", speed: "15 km/h", habitat: "Floodplains", discovered: "1837", dangerLevel: 3, funFact: "One of the first large dinosaurs, it could rear up on its hind legs to reach high vegetation.", image: "images/dinos/plateosaurus.jpg" },
    { name: "Eoraptor", era: "Triassic", diet: "Omnivore", length: "1m", weight: "10kg", speed: "40 km/h", habitat: "River Valleys", discovered: "1991", dangerLevel: 2, funFact: "Its name means 'dawn thief' — it lived at the very dawn of the age of dinosaurs.", image: "images/dinos/eoraptor.jpg" },
    { name: "Liliensternus", era: "Triassic", diet: "Carnivore", length: "5m", weight: "200kg", speed: "30 km/h", habitat: "Forests", discovered: "1934", dangerLevel: 6, funFact: "One of the largest predators of the Late Triassic, it may have hunted in packs.", image: "images/dinos/liliensternus.jpg" },
    { name: "Zupaysaurus", era: "Triassic", diet: "Carnivore", length: "4m", weight: "250kg", speed: "28 km/h", habitat: "Semi-arid Regions", discovered: "2003", dangerLevel: 5, funFact: "Its name means 'devil lizard' in the Quechua language of South America.", image: "images/dinos/zupaysaurus.jpg" },
    { name: "Pisanosaurus", era: "Triassic", diet: "Herbivore", length: "1m", weight: "9kg", speed: "25 km/h", habitat: "Open Woodlands", discovered: "1967", dangerLevel: 1, funFact: "May be the earliest known ornithischian dinosaur, though this classification is debated.", image: "images/dinos/pisanosaurus.png" },
    { name: "Melanorosaurus", era: "Triassic", diet: "Herbivore", length: "8m", weight: "1300kg", speed: "12 km/h", habitat: "Highlands", discovered: "1924", dangerLevel: 3, funFact: "Its name means 'Black Mountain lizard,' named after the Thaba Nyama mountains of South Africa.", image: "images/dinos/melanorosaurus.jpg" },
    { name: "Guaibasaurus", era: "Triassic", diet: "Omnivore", length: "2m", weight: "15kg", speed: "38 km/h", habitat: "Tropical Forests", discovered: "1999", dangerLevel: 2, funFact: "Named after the Rio Guaíba hydrographic basin in Brazil where it was discovered.", image: "images/dinos/guaibasaurus.png" },
    { name: "Thecodontosaurus", era: "Triassic", diet: "Herbivore", length: "2m", weight: "11kg", speed: "20 km/h", habitat: "Coastal Islands", discovered: "1836", dangerLevel: 1, funFact: "The 4th dinosaur ever named, its original fossils were destroyed in a WWII bombing raid on Bristol.", image: "images/dinos/thecodontosaurus.jpg" },
    { name: "Staurikosaurus", era: "Triassic", diet: "Carnivore", length: "2.2m", weight: "30kg", speed: "42 km/h", habitat: "Scrublands", discovered: "1970", dangerLevel: 3, funFact: "Named after the Southern Cross constellation, visible from Brazil where it was found.", image: "images/dinos/staurikosaurus.jpg" },
    { name: "Saltopus", era: "Triassic", diet: "Carnivore", length: "0.6m", weight: "1kg", speed: "50 km/h", habitat: "Desert Margins", discovered: "1910", dangerLevel: 1, funFact: "One of the tiniest dinosaurs ever found — it was roughly the size of a house cat.", image: "images/dinos/saltopus.jpg" },
    { name: "Mussaurus", era: "Triassic", diet: "Herbivore", length: "3m", weight: "70kg", speed: "18 km/h", habitat: "Lakeshores", discovered: "1979", dangerLevel: 2, funFact: "Its name means 'mouse lizard' because the first fossils found were tiny babies small enough to fit in a hand.", image: "images/dinos/mussaurus.jpg" },
    { name: "Procompsognathus", era: "Triassic", diet: "Carnivore", length: "1m", weight: "1kg", speed: "48 km/h", habitat: "Dry Uplands", discovered: "1913", dangerLevel: 1, funFact: "Made famous by Jurassic Park as venomous pack hunters, though no evidence supports this in reality.", image: "images/dinos/procompsognathus.jpg" },
    { name: "Aliwalia", era: "Triassic", diet: "Carnivore", length: "8m", weight: "1500kg", speed: "22 km/h", habitat: "River Deltas", discovered: "1985", dangerLevel: 8, funFact: "One of the largest land predators of the Triassic — a true apex predator of its time.", image: "images/dinos/aliwalia.jpg" },

    // ═══════════════════ JURASSIC ═══════════════════
    { name: "Stegosaurus", era: "Jurassic", diet: "Herbivore", length: "9m", weight: "5000kg", speed: "10 km/h", habitat: "Open Plains", discovered: "1877", dangerLevel: 5, funFact: "Its brain was the size of a walnut, yet its tail spikes (thagomizer) could deliver lethal blows.", image: "images/dinos/stegosaurus.jpg" },
    { name: "Brachiosaurus", era: "Jurassic", diet: "Herbivore", length: "26m", weight: "56000kg", speed: "8 km/h", habitat: "Conifer Forests", discovered: "1903", dangerLevel: 4, funFact: "Could reach heights of 16 meters — tall enough to peek into a 5th-floor window.", image: "images/dinos/brachiosaurus.jpg" },
    { name: "Allosaurus", era: "Jurassic", diet: "Carnivore", length: "9.5m", weight: "2300kg", speed: "34 km/h", habitat: "Semi-arid Floodplains", discovered: "1877", dangerLevel: 9, funFact: "The lion of the Jurassic — it may have hunted sauropods 10 times its own size in packs.", image: "images/dinos/allosaurus.jpg" },
    { name: "Diplodocus", era: "Jurassic", diet: "Herbivore", length: "27m", weight: "15000kg", speed: "12 km/h", habitat: "Fern Prairies", discovered: "1878", dangerLevel: 3, funFact: "Its tail could crack like a bullwhip at supersonic speeds, creating sonic booms to scare predators.", image: "images/dinos/diplodocus.jpg" },
    { name: "Apatosaurus", era: "Jurassic", diet: "Herbivore", length: "22m", weight: "22000kg", speed: "10 km/h", habitat: "Riverbanks", discovered: "1877", dangerLevel: 4, funFact: "Formerly called 'Brontosaurus' — the naming controversy lasted over a century before being resolved.", image: "images/dinos/apatosaurus.jpg" },
    { name: "Ceratosaurus", era: "Jurassic", diet: "Carnivore", length: "6m", weight: "900kg", speed: "30 km/h", habitat: "Wetlands", discovered: "1884", dangerLevel: 7, funFact: "Had a distinctive horn on its nose and was likely a powerful swimmer that hunted aquatic prey.", image: "images/dinos/ceratosaurus.jpg" },
    { name: "Dilophosaurus", era: "Jurassic", diet: "Carnivore", length: "7m", weight: "400kg", speed: "38 km/h", habitat: "Riverbeds", discovered: "1954", dangerLevel: 7, funFact: "Despite Jurassic Park, it had no frill and couldn't spit venom — but it was still a fearsome 7m predator.", image: "images/dinos/dilophosaurus.jpg" },
    { name: "Archaeopteryx", era: "Jurassic", diet: "Carnivore", length: "0.5m", weight: "0.5kg", speed: "N/A (flyer)", habitat: "Tropical Islands", discovered: "1861", dangerLevel: 1, funFact: "The most famous 'missing link' — half dinosaur, half bird — with feathered wings and a toothed jaw.", image: "images/dinos/archaeopteryx.jpg" },
    { name: "Camptosaurus", era: "Jurassic", diet: "Herbivore", length: "8m", weight: "850kg", speed: "15 km/h", habitat: "Coastal Plains", discovered: "1885", dangerLevel: 2, funFact: "Its name means 'flexible lizard' because it could walk on both two and four legs.", image: "images/dinos/camptosaurus.jpg" },
    { name: "Kentrosaurus", era: "Jurassic", diet: "Herbivore", length: "4.5m", weight: "1000kg", speed: "8 km/h", habitat: "Open Woodlands", discovered: "1915", dangerLevel: 5, funFact: "Had shoulder spikes over 60cm long — making it one of the most heavily armored herbivores.", image: "images/dinos/kentrosaurus.jpg" },
    { name: "Ornitholestes", era: "Jurassic", diet: "Carnivore", length: "2m", weight: "15kg", speed: "55 km/h", habitat: "Forest Edges", discovered: "1903", dangerLevel: 3, funFact: "Its name means 'bird robber' — it was fast enough to catch early birds and flying insects.", image: "images/dinos/ornitholestes.jpg" },
    { name: "Giraffatitan", era: "Jurassic", diet: "Herbivore", length: "23m", weight: "40000kg", speed: "7 km/h", habitat: "Tropical Forests", discovered: "1914", dangerLevel: 3, funFact: "Once classified as Brachiosaurus, it was reclassified in 2009 — its heart pumped 400 liters of blood per minute.", image: "images/dinos/giraffatitan.jpg" },
    { name: "Megalosaurus", era: "Jurassic", diet: "Carnivore", length: "9m", weight: "1000kg", speed: "28 km/h", habitat: "Floodplains", discovered: "1824", dangerLevel: 8, funFact: "The FIRST dinosaur ever scientifically named — kickstarting the entire field of paleontology.", image: "images/dinos/megalosaurus.jpg" },
    { name: "Compsognathus", era: "Jurassic", diet: "Carnivore", length: "1m", weight: "3kg", speed: "64 km/h", habitat: "Lagoon Islands", discovered: "1859", dangerLevel: 2, funFact: "One of the fastest dinosaurs ever — and for over a century, it was thought to be the smallest dinosaur.", image: "images/dinos/compsognathus.jpg" },
    { name: "Brontosaurus", era: "Jurassic", diet: "Herbivore", length: "22m", weight: "15000kg", speed: "10 km/h", habitat: "Conifer Forests", discovered: "1879", dangerLevel: 3, funFact: "Declared 'not a real dinosaur' in 1903, then resurrected as a valid genus in 2015 — a 112-year comeback.", image: "images/dinos/brontosaurus.jpg" },

    // ═══════════════════ CRETACEOUS ═══════════════════
    { name: "Tyrannosaurus Rex", era: "Cretaceous", diet: "Carnivore", length: "12m", weight: "8000kg", speed: "27 km/h", habitat: "Forests & Plains", discovered: "1905", dangerLevel: 10, funFact: "Had a bite force of 12,800 pounds — enough to crush a car and the strongest of any land animal ever.", image: "images/dinos/tyrannosaurus_rex.jpg" },
    { name: "Triceratops", era: "Cretaceous", diet: "Herbivore", length: "8m", weight: "9000kg", speed: "20 km/h", habitat: "Open Woodlands", discovered: "1889", dangerLevel: 6, funFact: "Its frill wasn't just for defense — it was filled with blood vessels and may have flushed with color.", image: "images/dinos/triceratops.jpg" },
    { name: "Velociraptor", era: "Cretaceous", diet: "Carnivore", length: "2m", weight: "15kg", speed: "60 km/h", habitat: "Arid Deserts", discovered: "1924", dangerLevel: 7, funFact: "Was actually turkey-sized and covered in feathers — not the 6-foot monsters shown in Jurassic Park.", image: "images/dinos/velociraptor.jpg" },
    { name: "Spinosaurus", era: "Cretaceous", diet: "Carnivore", length: "15m", weight: "7000kg", speed: "15 km/h", habitat: "Mangrove Swamps", discovered: "1912", dangerLevel: 9, funFact: "The largest carnivorous dinosaur ever — even bigger than T. Rex — and it could swim and hunt fish.", image: "images/dinos/spinosaurus.jpg" },
    { name: "Ankylosaurus", era: "Cretaceous", diet: "Herbivore", length: "8m", weight: "6000kg", speed: "10 km/h", habitat: "Forests", discovered: "1908", dangerLevel: 5, funFact: "Its tail club could shatter the bones of a T. Rex — it was the biological equivalent of a wrecking ball.", image: "images/dinos/ankylosaurus.jpg" },
    { name: "Pteranodon", era: "Cretaceous", diet: "Carnivore", length: "6m", weight: "20kg", speed: "80 km/h", habitat: "Coastal Cliffs", discovered: "1876", dangerLevel: 4, funFact: "Not actually a dinosaur but a flying reptile — its wingspan of 7m rivaled small aircraft.", image: "images/dinos/pteranodon.jpg" },
    { name: "Parasaurolophus", era: "Cretaceous", diet: "Herbivore", length: "10m", weight: "2700kg", speed: "25 km/h", habitat: "Swamp Forests", discovered: "1922", dangerLevel: 2, funFact: "Its hollow crest acted like a trumpet — it could produce deep, resonating calls heard for kilometers.", image: "images/dinos/parasaurolophus.jpg" },
    { name: "Iguanodon", era: "Cretaceous", diet: "Herbivore", length: "10m", weight: "3000kg", speed: "24 km/h", habitat: "Wetlands", discovered: "1825", dangerLevel: 3, funFact: "The second dinosaur ever named. Its thumb spike was originally placed on its nose like a horn!", image: "images/dinos/iguanodon.jpg" },
    { name: "Giganotosaurus", era: "Cretaceous", diet: "Carnivore", length: "13m", weight: "8000kg", speed: "32 km/h", habitat: "Open Plains", discovered: "1993", dangerLevel: 10, funFact: "Slightly larger than T. Rex but with a weaker bite — it likely used slashing attacks instead of crushing.", image: "images/dinos/giganotosaurus.jpg" },
    { name: "Gallimimus", era: "Cretaceous", diet: "Omnivore", length: "6m", weight: "440kg", speed: "72 km/h", habitat: "Open Steppes", discovered: "1972", dangerLevel: 2, funFact: "The ostrich-mimic dinosaur — one of the fastest dinosaurs, it could outrun modern racehorses.", image: "images/dinos/gallimimus.jpg" },
    { name: "Baryonyx", era: "Cretaceous", diet: "Carnivore", length: "10m", weight: "1700kg", speed: "25 km/h", habitat: "River Deltas", discovered: "1983", dangerLevel: 7, funFact: "Had massive 30cm claws and crocodile-like jaws — it was specialized for catching fish.", image: "images/dinos/baryonyx.jpg" },
    { name: "Carnotaurus", era: "Cretaceous", diet: "Carnivore", length: "8m", weight: "1300kg", speed: "48 km/h", habitat: "Arid Scrublands", discovered: "1985", dangerLevel: 8, funFact: "Had the tiniest arms of any large predator — even smaller proportionally than T. Rex.", image: "images/dinos/carnotaurus.jpg" },
    { name: "Pachycephalosaurus", era: "Cretaceous", diet: "Herbivore", length: "4.5m", weight: "450kg", speed: "30 km/h", habitat: "Upland Forests", discovered: "1943", dangerLevel: 4, funFact: "Its skull dome was 25cm thick — scientists debate whether it headbutted rivals like bighorn sheep.", image: "images/dinos/pachycephalosaurus.jpg" },
    { name: "Therizinosaurus", era: "Cretaceous", diet: "Herbivore", length: "10m", weight: "5000kg", speed: "12 km/h", habitat: "Dense Forests", discovered: "1954", dangerLevel: 6, funFact: "Had the longest claws of any animal ever — up to 1 meter long, used for pulling down tree branches.", image: "images/dinos/therizinosaurus.jpg" },
    { name: "Quetzalcoatlus", era: "Cretaceous", diet: "Carnivore", length: "11m", weight: "250kg", speed: "130 km/h", habitat: "Inland Plains", discovered: "1971", dangerLevel: 5, funFact: "The largest flying animal ever — with a 12m wingspan, it was as tall as a giraffe when standing.", image: "images/dinos/quetzalcoatlus.jpg" }
];

const fossils = [
    { name: "Sue (T-Rex)", category: "Skeleton", completeness: "90%", location: "South Dakota, USA", discovery: "1990", funFact: "Most complete T. Rex ever found. Sold at auction for $8.36 million — the most expensive fossil ever at the time.", image: "images/dinos/sue__t_rex_.jpg" },
    { name: "Archaeopteryx Lithographica", category: "Imprint", completeness: "95%", location: "Solnhofen, Germany", discovery: "1861", funFact: "Discovered just 2 years after Darwin published 'On the Origin of Species' — perfect timing to prove evolution.", image: "images/dinos/archaeopteryx_lithographica.jpg" },
    { name: "Big Al (Allosaurus)", category: "Skeleton", completeness: "95%", location: "Wyoming, USA", discovery: "1991", funFact: "CT scans revealed 19 injuries including broken ribs and a foot infection — Big Al lived a tough life.", image: "images/dinos/big_al__allosaurus_.jpg" },
    { name: "Dippy (Diplodocus)", category: "Cast", completeness: "100%", location: "Wyoming, USA", discovery: "1899", funFact: "Andrew Carnegie donated replica casts to museums worldwide — making it the most-seen dinosaur skeleton in history.", image: "images/dinos/dippy__diplodocus_.jpg" },
    { name: "Fighting Dinosaurs", category: "Fossilized Battle", completeness: "85%", location: "Gobi Desert, Mongolia", discovery: "1971", funFact: "A Velociraptor and Protoceratops locked in combat, preserved instantly by a collapsing sand dune.", image: "images/dinos/fighting_dinosaurs.jpg" },
    { name: "Amber Encased Feather", category: "Amber", completeness: "100%", location: "Myanmar", discovery: "2016", funFact: "Contains a piece of a feathered dinosaur tail from 99 million years ago — with visible color pigments.", image: "images/dinos/amber_encased_feather.jpg" },
    { name: "Triceratops Skull (Lane)", category: "Skull", completeness: "80%", location: "Montana, USA", discovery: "1988", funFact: "Triceratops skulls can be up to 2.5 meters long — among the largest skulls of any land animal.", image: "images/dinos/triceratops_skull__lane_.jpg" },
    { name: "Borealopelta", category: "Mummy", completeness: "100%", location: "Alberta, Canada", discovery: "2011", funFact: "The best-preserved armored dinosaur ever — you can still see its skin, scales, and even its last meal.", image: "images/dinos/borealopelta.jpg" }
];

const research = [
    { title: "Genetic Echoes", type: "Genetics", author: "Dr. Sattler", status: "Ongoing", image: "images/dinos/genetic_echoes.png", summary: "Analyzing surviving protein structures in preserved soft tissue to reconstruct dinosaur genomes.", details: "Using next-generation mass spectrometry, the team has identified collagen sequences in 68-million-year-old T. Rex bones that share similarities with modern chickens and ostriches." },
    { title: "Gobi Basin Excavation", type: "Expedition", author: "Dr. Grant", status: "Active", image: "images/dinos/gobi_basin_excavation.jpg", summary: "Unearthing the largest complete nesting ground of oviraptorosaurs ever discovered.", details: "The excavation has revealed over 100 fossilized eggs arranged in circular nesting patterns, suggesting complex brooding behaviors similar to modern birds." },
    { title: "Theropod Biomechanics", type: "Modeling", author: "Dr. Malcolm", status: "Published", image: "images/dinos/theropod_biomechanics.jpg", summary: "3D simulation of massive theropod running speeds and bite forces using computational modeling.", details: "Advanced musculoskeletal simulations reveal T. Rex could generate bite forces exceeding 12,800 pounds, while its maximum speed was likely around 27 km/h — slower than previously thought." },
    { title: "Sauropod Gigantism", type: "Analysis", author: "Dr. Harding", status: "Review", image: "images/dinos/sauropod_gigantism.png", summary: "Researching the biological limits of scale, metabolic rates, and oxygen levels in the Mesozoic.", details: "Higher Mesozoic oxygen levels (up to 30%) combined with a unique avian-style respiratory system allowed sauropods to reach sizes impossible for any mammal — up to 100 tonnes." }
];

if (typeof module !== 'undefined') {
    module.exports = { dinosaurs, fossils, research };
}
